config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :activity_logs do
    collection do
      get 'activity_logs_data', to: 'activity_logs#activity_log_data'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/remote_config.rb
class RemoteConfig < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  validates :user_name, presence: true, uniqueness: { case_sensitive: false }
  belongs_to :role

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:user_name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def login
    @login || self.user_name || self.email
  end
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  include RemotesHelper
  def index
    @babies = get_babies
    @assistants = get_assistants
  end

  def activity_log_data
    @activity_logs = get_activity_logs(params)
    render :layout => false
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    else
      "" end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/remotes_helper.rb
module RemotesHelper
  include HTTParty
  def get_activity_logs(params)
    data_response = []
    response = HTTParty.get((RemoteConfig.find_by_key('kinedu_ws').value + "/api/activity_logs?baby_id=#{params[:baby_id]}&assistant_id=#{params[:assistant_id]}&status=#{params[:status]}"), :headers => {"authorization" => 'K1N3DU'})
    data = JSON.parse response.body
    if data["status"] == "ok"
      data_response = data["response"]
    end
    data_response
  end

  def get_babies
    data_response = []
    response = HTTParty.get((RemoteConfig.find_by_key('kinedu_ws').value + '/api/babies'), :headers => {"authorization" => 'K1N3DU'})
    data = JSON.parse response.body
    if data["status"] == "ok"
      data_response = data["response"]
    end
    data_response
  end

  def get_assistants
    data_response = []
    response = HTTParty.get((RemoteConfig.find_by_key('kinedu_ws').value + '/api/assistants'), :headers => {"authorization" => 'K1N3DU'})
    data = JSON.parse response.body
    if data["status"] == "ok"
      data_response = data["response"]
    end
    data_response
  end
end

app/views/activity_logs/activity_log_data.html.erb
<table id="activity_logs_tb" class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Bebé</th>
    <th scope="col">Asistente</th>
    <th scope="col">Actividad</th>
    <th scope="col">Inicio</th>
    <th scope="col">Estamos</th>
    <th scope="col">Duración</th>
  </tr>
  </thead>
  <tbody id="activity_logs_tbody">
  <% @activity_logs.each do |activity_log| %>
    <tr>
      <td><%=activity_log["baby"] %></td>
      <td><%=activity_log["assistant"] %></td>
      <td><%=activity_log["activity"] %></td>
      <td><%=activity_log["start_time"] %></td>
      <td><%=activity_log["status"] %></td>
      <td><%=activity_log["duration"] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/activity_logs/index.html.erb
<div class="row">
  <div class="col-md-3">
    <select id="baby_select" class="select-picker">
      <option value="">Seleccionar bebé</option>
      <% @babies.each do |baby| %>
      <option value="<%=baby["id"] %>"> <%=baby["name"] %></option>
        <% end %>
    </select>
  </div>
  <div class="col-md-3">
    <select id="assistant_select" class="select-picker">
      <option value="">Seleccionar asistente</option>
      <% @assistants.each do |assistant| %>
        <option value="<%=assistant["id"] %>"> <%=assistant["name"] %></option>
      <% end %>
    </select>
  </div>
  <div class="col-md-3">
    <select id="status_select" class="select-picker">
      <option value="">Todos</option>
      <option value="1">Terminado</option>
      <option value="0'">En proceso</option>
    </select>
  </div>
  <div class="col-md-3" style="border: 1px #2E2F30">
    <button id="search_activity_logs_btn" type="button" class="btn btn-secondary">Buscar</button>
  </div>
  <div class="col-md-12" id="activity_log_data_div">

  </div>
</div>

<%= hidden_field_tag 'search_activity_logs_url', activity_logs_data_activity_logs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KineduWeb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to "KINEDU" , root_path, method: :get,class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Actividades" , activity_logs_path, method: :get,class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Perfil" , edit_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <li class="btn btn-outline-success my-2 my-sm-0"><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
      </form>
  <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Iniciar sesión" , new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Registrarse" , new_user_registration_path, method: :get,class: "nav-link" %>
        </li>
      </ul>
  <% end %>
  </div>
</nav>
<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class type %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><%= message %></p>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>